### PR TITLE
set path pointed to vocabulary - should be stage_vocabulary

### PR DESCRIPTION
**Pull request by rkboyce**

### CODE REVIEW

**Comment by leeevans** [comment]
@rkboyce  These changes look good except that in the OHDSI cloud CEM database the owner of the staging tables should be rw_grp;

Please update the alter table statements in create_eu_product_label_tables.sql from:

OWNER TO dikb;

to:

OWNER TO rw_grp;

and I will merge this pull request.

Thanks

**Comment by ericaVoss** [comment]
As long as Lee is okay with it, I'm okay with the Vocabulary name change (hopefully I didn't hard code it anywhere). 

Should I merge the request?

**Comment by rkboyce** [comment]
@leeevans - I fixed the 'OWNER TO rw_grp' in my branch and changed my postgres set up so that I will be  creating tables with that user going forward. Do you see that change?

**Comment by leeevans** [comment]
@rkboyce looks good,  I'll merge.

**Pull request merged**
